/*===========================================================================*/
/*                                                                           */
/* File    : WINDEB.H                                                        */
/*                                                                           */
/* Purpose :                                                                 */
/*                                                                           */
/* History :                                                                 */
/*                                                                           */
/* (C) Copyright 1989-1991 Marc Adler/Magma Systems     All Rights Reserved  */
/*===========================================================================*/

/*
  This is a NULL file which helps in porting WindowsMaker apps to MEWEL
*/
