/*===========================================================================*/
/*                                                                           */
/* File    : WINDOW.H                                                        */
/*                                                                           */
/* Purpose : Dummy Windows-compatible include file for MEWEL                 */
/*                                                                           */
/* History :                                                                 */
/*                                                                           */
/* (C) Copyright 1989-1994 Marc Adler/Magma Systems     All Rights Reserved  */
/*===========================================================================*/
#include "windows.h"

